#%RAML 0.8
title: RAML2
version: "2.1.1"
baseUri: "http://0.0.0.0:8081"
/resources:
    get:
        responses:
            "200":
                body:
                    text/plain:
                        example: hi dude