#%RAML 1.0
title: Sample API

/schema:
    put:
      body:
          application/json:
                schema: !include more spaces/schema.json
      responses:
            200:
                body:
                  application/json:
